services:
  postgres:
    image: postgres:18
    container_name: rideflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rideflow
      POSTGRES_PASSWORD: rideflow
      POSTGRES_DB: rideflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
